# -*- coding: utf-8 -*-
#
# GDX-Python documentation build configuration file, created by
# sphinx-quickstart on Mon Jun 18 18:37:19 2012.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys, os


class Mock(object):
    """Per http://read-the-docs.readthedocs.org/en/latest/faq.html#i-get-
    import-errors-on-libraries-that-depend-on-c-modules"""
    __all__ = []

    def __init__(self, *args, **kwargs):
        pass

    def __call__(self, *args, **kwargs):
        return Mock()

    @classmethod
    def __getattr__(cls, name):
        if name in ('__file__', '__path__'):
            return '/dev/null'
        elif name[0] == name[0].upper():
            mockType = type(name, (), {})
            mockType.__module__ = __name__
            return mockType
        else:
            return Mock()


MOCK_MODULES = ['gdxcc']
for mod_name in MOCK_MODULES:
    sys.modules[mod_name] = Mock()


# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath('../'))

# -- General configuration -----------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    ]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'pyGDX'
copyright = u'2012–2015, Paul Natsuo Kishimoto'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#

import gdx

# The short X.Y version.
version = gdx.__version__
# The full version, including alpha/beta/rc tags.
release = gdx.__version__

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []


# -- Options for HTML output ---------------------------------------------------

# on_rtd is whether we are on readthedocs.org, this line of code grabbed from docs.readthedocs.org
on_rtd = os.environ.get('READTHEDOCS', None) == 'True'

if not on_rtd:  # only import and set the theme if we're building docs locally
    import sphinx_rtd_theme
    html_theme = 'sphinx_rtd_theme'
    html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

# otherwise, readthedocs.org uses their theme by default, so no need to specify it

# Output file base name for HTML help builder.
htmlhelp_basename = 'pygdxdoc'


# -- Options for LaTeX output --------------------------------------------------

latex_elements = {
# The paper size ('letterpaper' or 'a4paper').
  'papersize': 'a5',

# The font size ('10pt', '11pt' or '12pt').
  'pointsize': '12pt',

# Additional stuff for the LaTeX preamble.
#'preamble': '',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual]).
latex_documents = [
  ('index', 'pygdx.tex', u'pyGDX Documentation',
   u'Paul Natsuo Kishimoto', 'manual'),
]


# -- Options for manual page output --------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'py-gdx', u'pyGDX Documentation',
     [u'Paul Natsuo Kishimoto'], 1)
]


# -- Options for Texinfo output ------------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
  ('index', 'py-gdx', u'pyGDX Documentation',
   u'Paul Natsuo Kishimoto', 'pyGDX', 'A Pythonic interface to GAMS GDX files.',
   'Miscellaneous'),
]


# -- Options for extensions ----------------------------------------------------
intersphinx_mapping = {
  'python': ('http://docs.python.org/3', None),
  'pandas': ('http://pandas.pydata.org/pandas-docs/stable/', None),
  'xray': ('http://xray.readthedocs.org/en/stable/', None),
  }

todo_include_todos = True
